# dbt Project Configuration
name: 'mds'  
version: '1.0.0'
config-version: 2

profile: 'mds'

model-paths: ["models"]  # Path for model SQL files
analysis-paths: ["analyses"]  # Path for analysis files
test-paths: ["tests"]  # Path for test files
seed-paths: ["seeds"]  # Path for seed data
macro-paths: ["macros"]  # Path for macro files
snapshot-paths: ["snapshots"]  # Path for snapshot files

clean-targets:
  - "target"
  - "dbt_packages"

vars: 
  bronze_schema: 'bronze'  
  silver_schema: 'silver'  
  gold_schema: 'gold'  

# Configuration for models
models:
  mds:
    bronze:  
      +materialized: view  a
    silver:  
      +materialized: table  
      dimensions:  
        +materialized: table
    gold:  
      +materialized: table  
      facts:  
        +materialized: table
