version: 2

sources:
  - name: bronze 
    database: coffee_shop  
    schema: bronze

    tables:
      - name: product 
        description: "Table containing product information"
        columns:
          - name: id
            description: "Primary key for product table"
          - name: unit_price
            description: "Price of the product"
          - name: category
            description: "Category of the product (e.g., Coffee, Tea)"
          - name: type
            description: "Type of product"
          - name: detail
            description: "Additional information about the product"

      - name: transaction  
        description: "Table containing transaction information"
        columns:
          - name: id
            description: "Primary key for transaction table"
          - name: date
            description: "Date of the transaction"
          - name: time
            description: "Time of the transaction"
          - name: quantity
            description: "Quantity of the product sold"
          - name: store_id
            description: "ID of the store where the transaction took place"
          - name: product_id
            description: "ID of the product involved in the transaction"

      - name: store 
        description: "Table containing store information"
        columns:
          - name: id
            description: "Primary key for store table"
          - name: location
            description: "Location of the store"
